/**
 * Generate the Swift activity map from the TypeScript catalog.
 *
 * The same name↔`HKWorkoutActivityType` table used to exist by hand in three places (the TS union,
 * the iOS plugin's switch, the watch's). Three hand-written copies of one table is a drift waiting
 * to happen, so the Swift is generated and compiled into BOTH targets.
 *
 * `HKWorkoutActivityType`'s Swift case names are the HealthKit constant with a lowercased first
 * letter — exactly the names in the catalog — so the emitted switch is an identity mapping the
 * COMPILER checks. A name that is not a real case fails the build loudly, which is the property
 * the old hand-written comment claimed and did not have.
 *
 * Run `npm run gen:workout-activities`; `npm run check:workout-activities` fails if it is stale.
 */
import { writeFileSync } from 'node:fs';
import { WORKOUT_ACTIVITIES } from '../src/workout-activities.ts';

const cases = WORKOUT_ACTIVITIES.map((a) => {
  if (!a.since) return `        case "${a.name}": return .${a.name}`;
  // Newer than our deployment floors: guard it, and answer `.other` on an OS that genuinely does
  // not have the case. Without this the file would not compile against the App target's floor.
  return [
    `        case "${a.name}":`,
    `            if #available(iOS ${a.since.ios}.0, watchOS ${a.since.watchos}.0, *) { return .${a.name} }`,
    `            return .other`,
  ].join('\n');
}).join('\n');

const swift = `// GENERATED by packages/cadence-shared/scripts/gen-workout-activities.ts — DO NOT EDIT.
// Source of truth: packages/cadence-shared/src/workout-activities.ts
// Regenerate with \`npm run gen:workout-activities\`; CI fails if this file is stale.
import Foundation
import HealthKit

/**
 The activity vocabulary, as HealthKit's own type.

 Compiled into BOTH the App target (the WorkoutKit hand-off plugin) and the CadenceWatch target
 (the live session), so the phone and the watch cannot disagree about what a session IS.

 Every case below is an identity mapping the compiler verifies: HealthKit's Swift case names are
 the constant with a lowercased first letter, which is exactly how the catalog names them. A name
 that is not a real case fails the build instead of silently becoming \`.other\`.
 */
extension HKWorkoutActivityType {
    /** The catalog name, or \`.other\` for anything unrecognised — the honest fallback for a
     *  payload from a newer phone than this build. */
    static func fromCadenceName(_ name: String) -> HKWorkoutActivityType {
        switch name {
${cases}
        default: return .other
        }
    }
}

extension HKWorkoutSessionLocationType {
    static func fromCadenceName(_ name: String) -> HKWorkoutSessionLocationType {
        switch name {
        case "outdoor": return .outdoor
        case "indoor": return .indoor
        default: return .unknown
        }
    }
}
`;

const out = new URL('../../../apps/cadence-ios/ios/App/Shared/WorkoutActivityMap.swift', import.meta.url);
writeFileSync(out, swift);
console.log(`wrote ${out.pathname} (${WORKOUT_ACTIVITIES.length} activities)`);
