import type { LegacySchemaFieldDef } from './types';

/**
 * LEGACY: Kept for backward compatibility with jobs that don't yet have
 * an expectedSchema. Will be removed once all jobs are migrated.
 */
export const ICP_SCHEMA_LEGACY: Record<string, LegacySchemaFieldDef> = {
  name: {
    label: 'Company Name',
    type: 'single',
    required: true,
    allowedValues: null /* free-text */,
  },
  /* icp_type removed — shelved for re-evaluation */
  size: {
    label: 'Size',
    type: 'single',
    required: false,
    allowedValues: ['SOHO (Micro)', 'Small', 'Medium', 'MSE (Mid-Size Enterprise)', 'Enterprise', 'Large Enterprise'],
  },
  employee_range: {
    label: 'Employee Range',
    type: 'single',
    required: false,
    allowedValues: [
      '1–10 employees',
      '11–50 employees',
      '51–250 employees',
      '251–1,000 employees',
      '1,001–5,000 employees',
      '5,001+ employees',
    ],
  },
  revenue_range: {
    label: 'Revenue Range',
    type: 'single',
    required: false,
    allowedValues: ['$0 — <$1M', '$1M — <$10M', '$10M — <$50M', '$50M — <$500M', '$500M — <$1B', '$1B — <$5B', '$5B+'],
  },
  vertical: {
    label: 'Vertical',
    type: 'multi',
    required: false,
    allowedValues: [
      'Healthcare',
      'Financial Services',
      'Retail',
      'Manufacturing',
      'Technology',
      'Education',
      'Real Estate',
      'Hospitality',
      'Transportation & Logistics',
      'Energy & Utilities',
      'Media & Entertainment',
      'Professional Services',
      'Construction',
      'Agriculture',
      'Telecommunications',
      'Government',
    ],
  },
  sub_vertical: {
    label: 'Sub-Vertical',
    type: 'multi',
    required: false,
    allowedValues: [
      /* Healthcare */ 'Hospitals & Health Systems',
      'Clinics & Ambulatory',
      'Pharma',
      'Medical Devices',
      'Health IT',
      'Payer / Insurance',
      /* Financial Services */ 'Banking',
      'Insurance',
      'Capital Markets',
      'Fintech',
      'Wealth Management',
      /* Retail */ 'E-commerce',
      'Brick & Mortar',
      'Grocery',
      'Specialty Retail',
      'Luxury',
      /* Manufacturing */ 'Discrete',
      'Process',
      'Automotive',
      'Aerospace & Defense',
      'Consumer Goods',
      /* Technology */ 'SaaS',
      'Hardware',
      'IT Services',
      'Cybersecurity',
      'AI / ML',
      'MSP',
      'Distributor',
      /* Education */ 'K-12',
      'Higher Education',
      'EdTech',
      'Corporate Training',
      /* Real Estate */ 'Commercial',
      'Residential',
      'Property Management',
      'REITs',
      /* Hospitality */ 'Hotels & Resorts',
      'Restaurants & Food Service',
      'Travel & Tourism',
      'Events',
      /* Transportation */ 'Freight & Shipping',
      'Last Mile',
      'Fleet Management',
      'Warehousing',
      /* Energy */ 'Oil & Gas',
      'Renewables',
      'Electric Utilities',
      'Water',
      'Energy Broker',
      /* Media */ 'Streaming',
      'Gaming',
      'Publishing',
      'Advertising',
      /* Professional Services */ 'Consulting',
      'Legal',
      'Accounting',
      'Staffing',
      /* Construction */ 'General Contracting',
      'Engineering',
      'Architecture',
      /* Agriculture */ 'Farming',
      'AgTech',
      'Food Processing',
      /* Telecommunications */ 'Wireless',
      'ISP',
      'Infrastructure',
      'Major Telco',
      /* Government */ 'Federal',
      'State & Local',
      'Defense',
      'Civilian Agencies',
    ],
  },
  business_model: {
    label: 'Business Model',
    type: 'multi',
    required: false,
    allowedValues: ['B2B', 'B2C', 'Hybrid'],
  },
  num_locations: {
    label: 'Number of Locations',
    type: 'single',
    required: false,
    allowedValues: null /* free-text number */,
  },
  ownership_type: {
    label: 'Ownership Type',
    type: 'multi',
    required: false,
    allowedValues: ['Private', 'Public', 'PE Backed', 'Non-profit', 'Government'],
  },
  operating_region: {
    label: 'Operating Region',
    type: 'multi',
    required: false,
    allowedValues: ['Any', 'US', 'Canada', 'EMEA', 'Africa', 'APAC'],
  },
  software_type: {
    label: 'Software Type',
    type: 'multi',
    required: false,
    allowedValues: [
      'HCM',
      'ERP',
      'CRM',
      'SCM',
      'BI / Analytics',
      'Collaboration',
      'Security',
      'DevOps',
      'iPaaS / Integration',
      'Vertical SaaS',
      'Infrastructure',
      'Fintech',
      'Martech',
      'Healthtech',
      'Edtech',
    ],
  },
  cbis: {
    label: 'Critical Business Issues',
    type: 'multi',
    required: false,
    allowedValues: null /* suggested values but custom accepted */,
    suggestedValues: [
      'Revenue Growth',
      'Cost Reduction',
      'Digital Transformation',
      'Customer Experience',
      'Operational Efficiency',
      'Risk & Compliance',
      'Market Expansion',
      'Innovation',
      'Talent Acquisition & Retention',
      'Sustainability',
    ],
  },
  pain_points: {
    label: 'Pain Points',
    type: 'multi',
    required: false,
    allowedValues: null /* suggested values but custom accepted */,
    suggestedValues: [
      'Manual Processes',
      'Data Silos',
      'Poor Visibility / Reporting',
      'Scaling Challenges',
      'Integration Issues',
      'Compliance Burden',
      'Talent Shortage',
      'Legacy Systems',
      'Customer Churn',
      'Security Concerns',
    ],
  },
  tech_stack: {
    label: 'Tech Stack',
    type: 'multi',
    required: false,
    allowedValues: null /* suggested values but custom accepted */,
    suggestedValues: [
      'Salesforce',
      'SAP',
      'Oracle',
      'Microsoft 365',
      'AWS',
      'Azure',
      'GCP',
      'HubSpot',
      'Workday',
      'ServiceNow',
      'Snowflake',
      'Tableau',
      'Slack',
      'Jira',
      'NetSuite',
    ],
  },
  tech_products_sold: {
    label: 'Tech Products Sold',
    type: 'multi',
    required: false,
    allowedValues: [
      'Connectivity',
      'Mobile',
      'CX',
      'SaaS',
      'AI',
      'Infrastructure',
      'Security',
      'Services',
      'Hardware',
      'Energy',
    ],
  },
  other_criteria: {
    label: 'Other Criteria',
    type: 'multi',
    required: false,
    allowedValues: null /* free-text tags */,
  },
  fortune_rank: {
    label: 'Fortune Rank',
    type: 'single',
    required: false,
    allowedValues: null,
  },
  ticker_symbol: {
    label: 'Ticker Symbol',
    type: 'single',
    required: false,
    allowedValues: null,
  },
  stock_exchange: {
    label: 'Stock Exchange',
    type: 'single',
    required: false,
    allowedValues: null,
  },
  locations: {
    label: 'Locations',
    type: 'multi',
    required: false,
    allowedValues: null,
  },
  general_contact: {
    label: 'General Contact',
    type: 'single',
    required: false,
    allowedValues: null,
  },
};
