// GENERATED by packages/cadence-shared/scripts/gen-workout-activities.ts — DO NOT EDIT.
// Source of truth: packages/cadence-shared/src/workout-activities.ts
// Regenerate with `npm run gen:workout-activities`; CI fails if this file is stale.
import Foundation
import HealthKit

/**
 The activity vocabulary, as HealthKit's own type.

 Compiled into BOTH the App target (the WorkoutKit hand-off plugin) and the CadenceWatch target
 (the live session), so the phone and the watch cannot disagree about what a session IS.

 Every case below is an identity mapping the compiler verifies: HealthKit's Swift case names are
 the constant with a lowercased first letter, which is exactly how the catalog names them. A name
 that is not a real case fails the build instead of silently becoming `.other`.
 */
extension HKWorkoutActivityType {
    /** The catalog name, or `.other` for anything unrecognised — the honest fallback for a
     *  payload from a newer phone than this build. */
    static func fromCadenceName(_ name: String) -> HKWorkoutActivityType {
        switch name {
        case "running": return .running
        case "walking": return .walking
        case "hiking": return .hiking
        case "cycling": return .cycling
        case "handCycling": return .handCycling
        case "swimming": return .swimming
        case "underwaterDiving":
            if #available(iOS 17.0, watchOS 10.0, *) { return .underwaterDiving }
            return .other
        case "rowing": return .rowing
        case "paddleSports": return .paddleSports
        case "sailing": return .sailing
        case "surfingSports": return .surfingSports
        case "crossCountrySkiing": return .crossCountrySkiing
        case "downhillSkiing": return .downhillSkiing
        case "snowboarding": return .snowboarding
        case "snowSports": return .snowSports
        case "skatingSports": return .skatingSports
        case "climbing": return .climbing
        case "equestrianSports": return .equestrianSports
        case "wheelchairWalkPace": return .wheelchairWalkPace
        case "wheelchairRunPace": return .wheelchairRunPace
        case "fishing": return .fishing
        case "hunting": return .hunting
        case "golf": return .golf
        case "traditionalStrengthTraining": return .traditionalStrengthTraining
        case "functionalStrengthTraining": return .functionalStrengthTraining
        case "highIntensityIntervalTraining": return .highIntensityIntervalTraining
        case "crossTraining": return .crossTraining
        case "coreTraining": return .coreTraining
        case "elliptical": return .elliptical
        case "stairClimbing": return .stairClimbing
        case "stairs": return .stairs
        case "stepTraining": return .stepTraining
        case "jumpRope": return .jumpRope
        case "pilates": return .pilates
        case "barre": return .barre
        case "yoga": return .yoga
        case "flexibility": return .flexibility
        case "preparationAndRecovery": return .preparationAndRecovery
        case "cooldown": return .cooldown
        case "mindAndBody": return .mindAndBody
        case "taiChi": return .taiChi
        case "gymnastics": return .gymnastics
        case "waterFitness": return .waterFitness
        case "mixedCardio": return .mixedCardio
        case "fitnessGaming": return .fitnessGaming
        case "play": return .play
        case "boxing": return .boxing
        case "kickboxing": return .kickboxing
        case "martialArts": return .martialArts
        case "wrestling": return .wrestling
        case "fencing": return .fencing
        case "cardioDance": return .cardioDance
        case "socialDance": return .socialDance
        case "danceInspiredTraining": return .danceInspiredTraining
        case "dance": return .dance
        case "soccer": return .soccer
        case "americanFootball": return .americanFootball
        case "australianFootball": return .australianFootball
        case "rugby": return .rugby
        case "basketball": return .basketball
        case "baseball": return .baseball
        case "softball": return .softball
        case "cricket": return .cricket
        case "hockey": return .hockey
        case "lacrosse": return .lacrosse
        case "volleyball": return .volleyball
        case "handball": return .handball
        case "waterPolo": return .waterPolo
        case "waterSports": return .waterSports
        case "tennis": return .tennis
        case "tableTennis": return .tableTennis
        case "badminton": return .badminton
        case "squash": return .squash
        case "racquetball": return .racquetball
        case "pickleball": return .pickleball
        case "discSports": return .discSports
        case "trackAndField": return .trackAndField
        case "bowling": return .bowling
        case "archery": return .archery
        case "curling": return .curling
        case "mixedMetabolicCardioTraining": return .mixedMetabolicCardioTraining
        case "other": return .other
        default: return .other
        }
    }
}

extension HKWorkoutSessionLocationType {
    static func fromCadenceName(_ name: String) -> HKWorkoutSessionLocationType {
        switch name {
        case "outdoor": return .outdoor
        case "indoor": return .indoor
        default: return .unknown
        }
    }
}
