/**
 * The coach mark: **Metronome Split** (BRAND.md + cadence-brand-identity-v2.md §9, locked
 * 2026-08-07 — supersedes the sunrise arch).
 *
 * Geometry is transcribed EXACTLY from the exported source of truth,
 * `docs/cadence/assets/cadence-mark-metronome-split.svg` (generated by
 * `cadence-icon-contact-sheet.html` → `conceptMetronomeSplit`, `dayNightC(14, 58)`). Do not
 * re-derive it by eye: the mark is a tuned letterform and small changes to weight or to where the
 * cut falls produce a different mark that still looks plausible. If it needs to change, change it
 * in the contact sheet, re-export, and re-transcribe.
 *
 * The only edit made to the export is the clip shapes. The generator emits each half-plane as a
 * ~100-point polyline (it supports curved splits); this cut is a straight 45° line, so the same
 * regions are expressed as two triangles. The boundaries are identical: x + y ≤ 116.6 and
 * x + y ≥ 123.4.
 *
 * Why the cut looks off-centre: it is. The letter is centred at (50,50) but the cut runs through
 * (60,60) — a perpendicular offset of ~14 units. That offset is the design. Centred, per the
 * contact sheet's own note, it "lops the top terminal off into a floating shard", and rotating the
 * letter to match the angle instead "costs the C its reading altogether".
 *
 * Fills are flat and solid — required by the iOS Icon Composer pipeline (one layered source →
 * Default/Dark/Mono) and correct under Liquid Glass, where the system renders depth itself.
 *
 * Keeps className="orb" so every existing size override (`.wordmark .orb`, `.consist .orb`,
 * `.welcome .hero .orb`, …) keeps working untouched.
 */
import { useId } from 'react';

/** The C: outer r=34, counter r=20 (thickness 14), 58° aperture facing east, centred (50,50). */
const C_PATH = 'M 79.737 66.484 A 34 34 0 1 1 79.737 33.516 L 66.773 39.107 A 20 20 0 1 0 66.773 60.893 Z';

/** Half-planes either side of the cut, with the export's 3.4-unit half-gap preserved. */
const DAY_CLIP = '-50,-50 166.6,-50 -50,166.6'; // x + y ≤ 116.6
const NIGHT_CLIP = '173.4,-50 173.4,173.4 -50,173.4'; // x + y ≥ 123.4

export function Orb({ className, hero = false }: { className?: string; hero?: boolean }) {
  const uid = useId().replace(/:/g, '');
  const dayClip = `ms-day-${uid}`;
  const nightClip = `ms-night-${uid}`;
  const cls = ['orb', hero ? 'orb-hero' : '', className].filter(Boolean).join(' ');
  return (
    <svg className={cls} viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <defs>
        <clipPath id={dayClip}>
          <polygon points={DAY_CLIP} />
        </clipPath>
        <clipPath id={nightClip}>
          <polygon points={NIGHT_CLIP} />
        </clipPath>
      </defs>
      {/* Day — the sun coral. Never brightened or further saturated: every step toward "energetic
          app orange" is a step toward reading as a Headspace cousin (identity doc §9). */}
      <path className="ms-day" d={C_PATH} fill="var(--sun)" clipPath={`url(#${dayClip})`} />
      {/* Night — dusk slate. Desaturated on purpose: sky at 9pm, never a link blue. */}
      <path className="ms-night" d={C_PATH} fill="var(--dusk)" clipPath={`url(#${nightClip})`} />
    </svg>
  );
}
